server:
  port: 8212
  name: tsid-auth-dev

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: url
    username: username
    password: password
  profiles:
    active: real
    include:
      - external
      - internal
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
  config:
    use-legacy-processing: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com:
      tsid:
        auth: error
  file:
    name: error.log
  register-shutdown-hook: false
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 7

elastic:
  apm:
    server-url: http://apm.tsidcert.com
    application-package: com.tsid.auth
    service-name: tsid-auth
    environment: production
    log-level: ERROR
    capture-body: all

tsid:
  fido:
    auth: auth
  sns:
    url: url
    auth: auth
  versatile:
    url: url

auth:
  temp:
    key: key
  di:
    key: key


jwt:
  secret: secret

rsa:
  private:
    key: key

